### ISSUE TITLE
Error in OpenId connection

### ISSUE THREAD

**Issue by osallou** [bbangert/velruse#109]
Hi,
I face an authentication error with an openid provider (openid.com) that usually works on other sites (not velruse related).

My colleagues could login with google or other openids in our app, but I fails with mine (*.myopenid.com)

Here is stack log.

Any way to debug/fix this?

Thanks

<pre>
2013-02-19 18:08:34,894 ERROR [gunicorn.error][GreenThread-83] Error handling request
Traceback (most recent call last):
  File "/root/mobyle2/local/lib/python2.7/site-packages/gunicorn/workers/async.py", line 45, in handle
    self.handle_request(listener, req, client, addr)
  File "/root/mobyle2/local/lib/python2.7/site-packages/gunicorn/workers/async.py", line 93, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/root/mobyle2/local/lib/python2.7/site-packages/newrelic-1.10.0.28/newrelic/api/web_transaction.py", line 765, in __call__
    result = application(environ, _start_response)
  File "/root/mobyle2/local/lib/python2.7/site-packages/newrelic-1.10.0.28/newrelic/api/object_wrapper.py", line 220, in __call__
    self._nr_instance, args, kwargs)
  File "/root/mobyle2/local/lib/python2.7/site-packages/newrelic-1.10.0.28/newrelic/api/function_trace.py", line 93, in literal_wrapper
    return wrapped(*args, **kwargs)
  File "/root/mobyle2/local/lib/python2.7/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/root/mobyle2/local/lib/python2.7/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/root/mobyle2/local/lib/python2.7/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/root/mobyle2/local/lib/python2.7/site-packages/pyramid/router.py", line 117, in handle_request
    root = root_factory(request)
  File "/root/mobyle2/local/lib/python2.7/site-packages/velruse/providers/openid.py", line 246, in callback
    raise ThirdPartyFailure("No OpenID Session has begun.")
ThirdPartyFailure: No OpenID Session has begun.
</pre>

**Comment by mmerickel** [comment]
I added an OpenID test focused on myopenid.com. It's working so I'm not sure what your issue is. Maybe you can tell me what options you're trying to use with velruse otherwise it's going to be hard for me to help.

https://github.com/bbangert/velruse/commit/4657ceeb2e0a259357a2d2bacddba2f2a968928c

**Comment by osallou** [comment]
I gonna retest with latest code. Maybe with your updates (or on myopenid side), it's working now...
